services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./backend/open_webui:/app/backend/open_webui
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    env_file:
      - .env
    environment:
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
